/**
 * @fileoverview Auto-generated OODA loop catalog
 * DO NOT EDIT MANUALLY - Generated by scripts/embed-loops.ts
 * Source: .claude/commands/loops/
 * @module src/resources/loops-content
 */

export interface LoopMetadata {
  type: string;
  speed: string;
  scope: string;
  description: string;
  interface_version: string;
  inputs: unknown[];
  outputs: unknown[];
  signals: unknown[];
  composition: Record<string, unknown>;
}

export interface Loop {
  content: string;
  metadata: LoopMetadata;
}

export interface LoopsCatalog {
  [category: string]: {
    [loopName: string]: Loop;
  };
}

export const LOOPS_CATALOG: LoopsCatalog = {
} as const;

/**
 * Get all available categories
 */
export function getCategories(): string[] {
  return Object.keys(LOOPS_CATALOG);
}

/**
 * Get all loops in a category
 */
export function getLoopsInCategory(category: string): string[] {
  const cat = LOOPS_CATALOG[category];
  if (!cat) {
    throw new Error(`Category not found: ${category}. Available: ${getCategories().join(", ")}`);
  }
  return Object.keys(cat);
}

/**
 * Get a specific loop by category and name
 */
export function getLoop(category: string, name: string): Loop {
  const cat = LOOPS_CATALOG[category];
  if (!cat) {
    throw new Error(`Category not found: ${category}. Available: ${getCategories().join(", ")}`);
  }
  const loop = cat[name];
  if (!loop) {
    throw new Error(`Loop not found: ${name} in category ${category}. Available: ${Object.keys(cat).join(", ")}`);
  }
  return loop;
}