/**
 * Validator service — runs notebook code cells as deterministic predicates
 * over JSON-serialisable observed data.
 *
 * Design notes:
 * - Bindings are frozen at PLAN time. A binding stores a deep copy of the
 *   cell source plus the resolved package.json/tsconfig, plus a sha256 hash
 *   of that snapshot. Validation runs against the snapshot in a fresh temp
 *   dir — never re-reads the live notebook — so post-bind notebook edits
 *   cannot influence verdicts.
 * - Verdict channel is a sidecar JSON file. The cell reads
 *   `process.env.TB_OBSERVED_PATH` (the JSON-serialised observed data) and
 *   writes `process.env.TB_VERDICT_PATH` (a `{verdict, reason, evidence?}`
 *   document). Stdout/stderr are captured for audit but never parsed.
 * - A small helper module `tb-validate.ts` is materialised next to the cell
 *   so validators can `import { observed, pass, fail } from "./tb-validate.js"`.
 */

import { createHash } from "node:crypto";
import * as fs from "node:fs/promises";
import * as os from "node:os";
import * as path from "node:path";
import { NotebookStateManager } from "./state.js";
import {
  buildDefaultPackageJson,
  buildDefaultTsconfig,
  type CodeCell,
  type CodeLanguage,
  type ValidatorBinding,
  type ValidatorSnapshot,
  type ValidatorVerdict,
  type ValidationResult,
} from "./types.js";
import { executeJavaScript, executeTypeScript } from "./execution.js";

const TB_VALIDATE_HELPER_JS = `// Auto-generated by Thoughtbox ValidatorService.
import { readFileSync, writeFileSync } from "node:fs";
export function observed() {
  const p = process.env.TB_OBSERVED_PATH;
  if (!p) throw new Error("TB_OBSERVED_PATH not set");
  return JSON.parse(readFileSync(p, "utf8"));
}
function write(verdict, reason, evidence) {
  const p = process.env.TB_VERDICT_PATH;
  if (!p) throw new Error("TB_VERDICT_PATH not set");
  writeFileSync(p, JSON.stringify({ verdict, reason, evidence }));
}
export function pass(reason, evidence) { write("pass", reason, evidence); }
export function fail(reason, evidence) { write("fail", reason, evidence); }
`;

const TB_VALIDATE_HELPER_TS = `// Auto-generated by Thoughtbox ValidatorService.
import { readFileSync, writeFileSync } from "node:fs";
export function observed<T = unknown>(): T {
  const p = process.env.TB_OBSERVED_PATH;
  if (!p) throw new Error("TB_OBSERVED_PATH not set");
  return JSON.parse(readFileSync(p, "utf8")) as T;
}
function write(verdict: "pass" | "fail", reason: string, evidence?: unknown): void {
  const p = process.env.TB_VERDICT_PATH;
  if (!p) throw new Error("TB_VERDICT_PATH not set");
  writeFileSync(p, JSON.stringify({ verdict, reason, evidence }));
}
export function pass(reason: string, evidence?: unknown): void { write("pass", reason, evidence); }
export function fail(reason: string, evidence?: unknown): void { write("fail", reason, evidence); }
`;

const VALIDATION_TIMEOUT_MS = 30_000;

export interface ValidatorRunOptions {
  /** Optional override for the validator subprocess timeout. */
  timeoutMs?: number;
  /** Optional integrity check; if provided and mismatches the binding hash, run is refused. */
  expectedSnapshotHash?: string;
}

export class ValidatorService {
  private readonly tempRoot: string;

  constructor(
    private readonly state: NotebookStateManager,
    tempRoot?: string,
  ) {
    this.tempRoot =
      tempRoot ?? path.join(os.tmpdir(), "thoughtbox-validator-runs");
  }

  /**
   * Resolve a notebook cell to a frozen binding. Captures the cell source,
   * package.json, and tsconfig (if any) so the validator becomes immune to
   * later notebook edits.
   */
  async bind(notebookId: string, cellId: string): Promise<ValidatorBinding> {
    const notebook = this.state.getNotebook(notebookId);
    if (!notebook) {
      throw new Error(`Notebook ${notebookId} not found`);
    }
    const cell = notebook.cells.find((c) => c.id === cellId);
    if (!cell) {
      throw new Error(`Cell ${cellId} not found in notebook ${notebookId}`);
    }
    if (cell.type !== "code") {
      throw new Error(
        `Cell ${cellId} is not a code cell (type: ${cell.type}); validators must be code cells.`,
      );
    }
    const codeCell = cell as CodeCell;

    const pkgCell = notebook.cells.find((c) => c.type === "package.json");
    const packageJson =
      pkgCell && pkgCell.type === "package.json"
        ? pkgCell.source
        : buildDefaultPackageJson(notebook.language);

    const tsconfig =
      notebook.language === "typescript"
        ? notebook["tsconfig.json"] ?? buildDefaultTsconfig()
        : undefined;

    const snapshot: ValidatorSnapshot = {
      source: codeCell.source,
      packageJson,
      ...(tsconfig !== undefined ? { tsconfig } : {}),
    };

    return {
      notebookId,
      cellId,
      language: codeCell.language,
      filename: codeCell.filename,
      snapshot,
      snapshotHash: hashSnapshot(snapshot),
      boundAt: new Date().toISOString(),
    };
  }

  /**
   * Execute a binding against `observed`. Returns a structured verdict.
   */
  async run(
    binding: ValidatorBinding,
    observed: unknown,
    options: ValidatorRunOptions = {},
  ): Promise<ValidationResult> {
    const expectedSnapshotHash = options.expectedSnapshotHash;
    const liveHash = hashSnapshot(binding.snapshot);

    if (
      expectedSnapshotHash !== undefined &&
      expectedSnapshotHash !== liveHash
    ) {
      return {
        pass: false,
        reason: "snapshot_hash_mismatch",
        snapshotHash: liveHash,
        hashMatched: false,
        exitCode: null,
        stdout: "",
        stderr: "",
      };
    }

    await fs.mkdir(this.tempRoot, { recursive: true });
    const runDir = await fs.mkdtemp(
      path.join(this.tempRoot, "validator-"),
    );
    const srcDir = path.join(runDir, "src");
    await fs.mkdir(srcDir, { recursive: true });

    const observedPath = path.join(runDir, "observed.json");
    const verdictPath = path.join(runDir, "verdict.json");
    const cellPath = path.join(srcDir, binding.filename);
    const helperFilename =
      binding.language === "typescript" ? "tb-validate.ts" : "tb-validate.js";
    const helperPath = path.join(srcDir, helperFilename);
    const helperSource =
      binding.language === "typescript"
        ? TB_VALIDATE_HELPER_TS
        : TB_VALIDATE_HELPER_JS;

    try {
      await fs.writeFile(
        observedPath,
        JSON.stringify(observed ?? null),
        "utf8",
      );
      await fs.writeFile(
        path.join(runDir, "package.json"),
        binding.snapshot.packageJson,
        "utf8",
      );
      if (binding.snapshot.tsconfig !== undefined) {
        await fs.writeFile(
          path.join(runDir, "tsconfig.json"),
          binding.snapshot.tsconfig,
          "utf8",
        );
      }
      await fs.writeFile(cellPath, binding.snapshot.source, "utf8");
      await fs.writeFile(helperPath, helperSource, "utf8");

      const execOptions = {
        cwd: runDir,
        env: {
          TB_OBSERVED_PATH: observedPath,
          TB_VERDICT_PATH: verdictPath,
          TB_VALIDATE: "1",
        },
        timeout: options.timeoutMs ?? VALIDATION_TIMEOUT_MS,
      };

      const result =
        binding.language === "typescript"
          ? await executeTypeScript(cellPath, execOptions)
          : await executeJavaScript(cellPath, execOptions);

      const verdict = await readVerdict(verdictPath);

      if (!verdict) {
        // Distinguish three failure modes:
        //   exitCode === -1  → killed by timeout (or fatal spawn error)
        //   exitCode  > 0    → cell threw / process crashed before writing verdict
        //   exitCode === 0   → cell ran to completion but no/bad verdict file
        const reason =
          result.exitCode === -1
            ? "validator_timeout_or_crash"
            : result.exitCode !== 0 && result.exitCode !== null
              ? "validator_crash"
              : "malformed_verdict";
        return {
          pass: false,
          reason,
          snapshotHash: liveHash,
          hashMatched: true,
          exitCode: result.exitCode,
          stdout: result.stdout,
          stderr: result.stderr,
        };
      }

      return {
        pass: verdict.verdict === "pass",
        reason: verdict.reason,
        ...(verdict.evidence !== undefined ? { evidence: verdict.evidence } : {}),
        snapshotHash: liveHash,
        hashMatched: true,
        exitCode: result.exitCode,
        stdout: result.stdout,
        stderr: result.stderr,
      };
    } finally {
      await fs.rm(runDir, { recursive: true, force: true }).catch(() => {});
    }
  }
}

function hashSnapshot(snapshot: ValidatorSnapshot): string {
  const canonical = JSON.stringify({
    source: snapshot.source,
    packageJson: snapshot.packageJson,
    tsconfig: snapshot.tsconfig ?? null,
  });
  return createHash("sha256").update(canonical, "utf8").digest("hex");
}

async function readVerdict(verdictPath: string): Promise<ValidatorVerdict | null> {
  let raw: string;
  try {
    raw = await fs.readFile(verdictPath, "utf8");
  } catch {
    return null;
  }
  try {
    const parsed = JSON.parse(raw);
    if (
      parsed &&
      typeof parsed === "object" &&
      (parsed.verdict === "pass" || parsed.verdict === "fail") &&
      typeof parsed.reason === "string"
    ) {
      const result: ValidatorVerdict = {
        verdict: parsed.verdict,
        reason: parsed.reason,
      };
      if ("evidence" in parsed) {
        result.evidence = parsed.evidence;
      }
      return result;
    }
    return null;
  } catch {
    return null;
  }
}

/** Convenience helper for callers that hold a notebookId/cellId pair. */
export async function bindAndRun(
  service: ValidatorService,
  notebookId: string,
  cellId: string,
  observed: unknown,
): Promise<{ binding: ValidatorBinding; result: ValidationResult }> {
  const binding = await service.bind(notebookId, cellId);
  const result = await service.run(binding, observed);
  return { binding, result };
}

export { hashSnapshot };
